version: "2.3"

services:
   redis:
      image: redis
      command: ["redis-server", "--appendonly", "yes"]
      hostname: redis
      container_name: redis
      ports:
         - "6379:6379"
      networks:
         - qcnet
      volumes:
         - /opt/qcloud/redis:/data


   rabbitmq:
      image: rabbitmq
      hostname: rabbitmq
      container_name: rabbitmq
      ports:
         - "5672:5672"
         - "15672:15672"
      networks:
         - qcnet


   qcauth:
      image: qcauth:1.0.0
      build: qcauth
      hostname: qcauth
      container_name: qcauth
      depends_on:
         - redis
      ports:
         - "8882:8882"
      networks:
         - qcnet
      volumes:
         - type:    bind
           source: ./config/qcloud.cfg
           target: /opt/qcloud/qcloud.cfg


   monitor:
      image: qcmon:1.0.0
      build: qcmon
      hostname: qcmon
      container_name: qcmon
      networks:
         - qcnet
      volumes:
         - /shared/qcloud:/shared/qcloud
         - type:    bind
           source: ./config/qcloud.cfg
           target: /opt/qcloud/qcloud.cfg


   qcweb:
      image: qcweb:1.0.0
      build: qcweb
      container_name: qcweb
      hostname: qcweb
      command: ["qcweb"]
      ports:
         - "8883:8883"
      depends_on:
         - "qcauth"
      networks:
         - qcnet
      volumes:
         - /shared/qcloud:/shared/qcloud
         - /opt/qcloud/egress.pipe:/opt/qcloud/egress.pipe
         - /opt/qcloud/ingress.pipe:/opt/qcloud/ingress.pipe
         - /opt/qcloud/bin/sbatch:/opt/slurm/bin/sbatch
         - /opt/qcloud/bin/squeue:/opt/slurm/bin/squeue
         - /opt/qcloud/bin/scancel:/opt/slurm/bin/scancel
         - type:    bind
           source: ./config/qcloud.cfg
           target: /opt/qcloud/qcloud.cfg


networks:
   qcnet:
     driver: bridge
     name: qcnet
